# Generated by Django 4.0.4 on 2022-05-21 16:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('middle_name', models.CharField(blank=True, default='', max_length=50)),
                ('age', models.IntegerField()),
                ('sex', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], default='female', max_length=6)),
                ('nationality', models.CharField(max_length=50)),
                ('state_of_origin', models.CharField(max_length=50)),
                ('marriage_status', models.CharField(choices=[('married', 'Married'), ('single', 'Single')], default='single', max_length=10)),
                ('address', models.CharField(max_length=300)),
                ('religion', models.CharField(max_length=50)),
                ('tribe', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='LabAppointmentHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('report', models.TextField()),
                ('next_appointment_date', models.DateField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.patient')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='DoctorAppointmentHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('hospital_section', models.CharField(max_length=50)),
                ('presenting_complain', models.TextField(default='')),
                ('history_of_presenting_complain', models.TextField(default='')),
                ('past_medical_and_surgical_history', models.TextField(default='')),
                ('drugs_and_allergies', models.TextField(default='')),
                ('family_and_social_history', models.TextField(default='')),
                ('other_history', models.TextField(default='')),
                ('provisional_diagnosis', models.TextField(default='')),
                ('physical_examination', models.TextField(default='')),
                ('lab_appointment', models.TextField(default='None')),
                ('next_appointment_date', models.DateField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.patient')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
