# Generated by Django 4.0.4 on 2022-05-21 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='labappointmenthistory',
            name='image_report',
            field=models.FileField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='patient',
            name='hospital_number',
            field=models.IntegerField(default=0, unique=True),
        ),
    ]
