# Generated by Django 4.0.4 on 2022-06-06 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_doctorappointmenthistory_drugs_and_allergies_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='hospital_number',
        ),
        migrations.AddField(
            model_name='patient',
            name='hospital_id',
            field=models.CharField(blank=True, max_length=64, unique=True),
        ),
    ]
