# Generated by Django 4.0.4 on 2022-06-19 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_customuser_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='is_clerical_staff',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_doctor',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_lab_staff',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
